### ISSUE TITLE
[Semanário] Princípios para decisões de design

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/lista-utilidades#1]
* [Design Principles](https://www.gov.uk/guidance/government-design-principles). Somente princípio 1 - Start with user needs. Não é necessário seguir os links com material adicional

* [8 principles of Open Government Data](https://opengovdata.org/). Somente princípio 2.Primary

* [Fiscal Transparency Principles](https://www.imf.org/external/np/fad/trans/Code2019.pdf). Somente itens 1.3, 1.3.1, 1.3.2, 1.3.3
* [Data on the Web Best Practices (BP)](https://www.w3.org/TR/dwbp/). Somente as caixas das melhores práticas. Esse documento possui [tradução](http://www.w3c.br/traducoes/DWBP-pt-br/)
    * [BP15: Reuse vocabularies, preferably standardized ones](https://www.w3.org/TR/dwbp/#ReuseVocabularies)
    * [BP31: Enrich data by generating new data](https://www.w3.org/TR/dwbp/#EnrichData)
    * [BP32: Provide Complementary Presentations](https://www.w3.org/TR/dwbp/#ProvideComplementaryPresentations)

**Comment by fjuniorr** [comment]
:+1:

**Comment by kesiabomfa** [comment]
+1

**Comment by kesiabomfa** [comment]
:+1:

**Comment by Andrelamor** [comment]
:+1:
[complementação do primeiro link](https://apolitical.co/o-que-realmente-significa-digital/?utm_campaign=Boot%20Camps%2FCourse%20Drips&utm_source=hs_email&utm_medium=email&utm_content=82081388&_hsenc=p2ANqtz-9-HLYLCgDpjympJ3B39yCXlpn2jJ7GKbOB0zkIEj8Ii8lK9uw3oYjHX2YT9mAA6FitPD8ASEElaS12zDXoix4kwy-M8ye_fTcS3dAA8qsPFYluAA0&_hsmi=82081388), _starting with user needs_;

[o exemplo do segundo](https://www.whitehouse.gov/sites/default/files/omb/memoranda/2013/m-13-13.pdf), _primary_, está quebrado

**Comment by fjuniorr** [comment]
O [White House M-13-13 (2013)](https://digital.gov/open-data-policy-m-13-13/), que estava com o link quebrado, é um memorando direcionado aos chefes de departamentos e agências do governo federal dos EUA que define que dados abertos devem ser consistentes com o princípio da completude, [definido](https://obamawhitehouse.archives.gov/sites/default/files/omb/memoranda/2013/m-13-13.pdf#page=4) como:

> Complete. Open data are published in primary forms (i.e., as collected at the source), with the finest possible level of granularity that is practicable and permitted by law and other requirements. Derived or aggregate open data should also be published but must reference the primary data.

**Comment by silvianafaria** [comment]
:+1:

**Comment by silvianafaria** [comment]
Ao ler os princípios do segundo link fiquei com uma enorme dúvida:  A extração do Portal de Transparência obedece o princípio "Primary"?

**Comment by Andrelamor** [comment]
> Ao ler os princípios do segundo link fiquei com uma enorme dúvida: A extração do Portal de Transparência obedece o princípio "Primary"?

Pelo que entendi, todo dado primário que uma organização opta por transformar/processar, deve ser paralelamente fornecido em formato aberto, para registro histórico, consumo e processamento por qq interessado externo
