### ISSUE TITLE
[Semanário] Cópia de base de dados vs extração de dados

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/lista-utilidades#2]
* Quem tem medo da transparência? Avanços da ciência de dados e da tecnologia da informação abrem caminho para uma nova estratégia de controle e contribuição para um governo mais eficiente. [Blogpost](https://medium.com/inova%C3%A7%C3%A3o-em-governo-e-no-controle/quem-tem-medo-da-transpar%C3%AAncia-26edbd23cd75) do [Daniel Lima Ribeiro](https://www.linkedin.com/in/daniel-lima-ribeiro-82437869/?originalSubdomain=br), Coordenador do [Laboratório de Inovação do Ministério Público do Estado do Rio de Janeiro](https://www.conjur.com.br/2019-out-05/laboratorio-inovacao-usa-tecnologia-aumentar-eficacia-mp-rj).

**Comment by silvianafaria** [comment]
:+1:

**Comment by Andrelamor** [comment]
* Primeira impressão ao ler o artigo [Laboratório de Inovação usa Tecnologia para aumentar a eficiência do MP-RJ](https://www.conjur.com.br/2019-out-05/laboratorio-inovacao-usa-tecnologia-aumentar-eficacia-mp-rj) é a ausência ou insuficiência de práticas do poder executivo, ou dos formuladores de políticas públicas, para verificar questões triviais que seriam de sua competência (lembrando que a 'primeira linha de defesa' está na própria gestão). Um exemplo citado no artigo foi o envio de fotos pelos alunos para avaliação da qualidade da merenda - isso é inovação? Temos um [exemplo caseiro na CGE](http://cge.mg.gov.br/projetos-especiais/cge-presente/1-ciclo-alimentacao-escolar) de uma forma de abordar essa questão que envolveu os responsáveis diretos pela ação. 

* Outro aspecto negativo, o Ministério Público precisar montar uma estrutura própria de sistema de dados é também agir sob a ineficiência ou recusa do executivo em prover os dados - custos de obtenção da informação suportados pelo contribuinte.

* Consequências positivas percebidas na leitura dos dois artigos: 
1) A preocupação do pessoal do Ministério Público em sair do escritório e conhecer a realidade fática;
2) A postura mais dialógica assumida quando se evita judicialização. A princípio, mais favorável para encaminhamentos de questões apontadas pelas estruturas de controle

**Comment by fjuniorr** [comment]
De fato esse artigo também traz pontos interessantes. Algumas reflexões sobre o que você disse:

> Um exemplo citado no artigo foi o envio de fotos pelos alunos para avaliação da qualidade da merenda - isso é inovação? Temos um exemplo caseiro na CGE de uma forma de abordar essa questão que envolveu os responsáveis diretos pela ação.

Eu considero o envio de fotos pelos alunos para avaliação da qualidade da merenda uma inovação pois a CGU está utilizando uma fonte (eg. alunos) de evidência (eg. foto) e um meio de comunicação (eg. celular) que supostamente até então não era utilizado para avaliar a qualidade da merenda. O fato da iniciativa da CGE envolver o gestor, e isso potencialmente ser um modo de agir "melhor" em alguma dimensão, não diminui o aspecto de inovação que ocorreu na auditoria/fiscalização tradicional da CGU.

> Outro aspecto negativo, o Ministério Público precisar montar uma estrutura própria de sistema de dados é também agir sob a ineficiência ou recusa do executivo em prover os dados - custos de obtenção da informação suportados pelo contribuinte.

No [blogpost original](https://medium.com/inova%C3%A7%C3%A3o-em-governo-e-no-controle/quem-tem-medo-da-transpar%C3%AAncia-26edbd23cd75) o Daniel afirmou que "tudo custa dinheiro". Esse tipo de argumento foca a discussão de qual mecanismo possui menor "custo de obtenção de informação", pois todos terão um custo associado que em última instância vai ser suportado pelo contribuinte. O ponto passa a ser como garantir que todos os atores interessados possam "reusar" as cópias dos bancos de dados, sem necessidade de manutenção de estrutura própria. "Repassar" o custo para o gestor não vai resolver.

Em outra nota, a CGE também está tentando adotar uma estratégia de buscar acesso às bases de dados dos sistemas corporativos, e não somente a extração de dados dos mesmos. Isso começou com a alteração deste dispositivo da [Lei 22.257/2016](https://www.almg.gov.br/consulte/legislacao/completa/completa-nova-min.html?tipo=LEI&num=22257&comp=&ano=2016&texto=consolidado)

> Art. 48, § 3º – Os órgãos e entidades da administração pública estadual e as entidades privadas encarregadas da administração ou gestão de recursos públicos estaduais __fornecerão as informações, os documentos e os processos requisitados pela CGE__ para o cumprimento das competências previstas no caput, salvo nas hipóteses expressamente previstas em lei.

para

> Art. 49, § 3º – __A CGE terá acesso irrestrito a processos, documentos, registros, operações, dados e quaisquer outras informações requisitadas__, inclusive aquelas armazenadas em sistemas corporativos do Estado, salvo nas hipóteses expressamente previstas em lei.

pela [Lei 23.304/2019](https://www.almg.gov.br/consulte/legislacao/completa/completa-nova-min.html?tipo=LEI&num=23304&comp=&ano=2019&texto=consolidado). Esse dispositivo existia no [Decreto nº 47.139/2017](https://www.almg.gov.br/consulte/legislacao/completa/completa.html?tipo=DEC&num=47139&comp=&ano=2017), afirmando que a Auditora-Geral deverá ter acesso irrestrito a processos, documentos, registros, operações, dados e quaisquer outras informações requisitadas, inclusive aquelas armazenadas em sistemas corporativos do Estado mas seu escopo foi bastante ampliado.
