### ISSUE TITLE
[Semanário] Regras de etiquetas para comunicação assíncrona

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/lista-utilidades#4]
* [15 rules for communicating at GitHub](https://ben.balter.com/2014/11/06/rules-of-communicating-at-github/). Ben Balter. 2014

**Comment by Andrelamor** [comment]
A comunicação assíncrona exige muita disciplina e adoção de normas comuns, e é isso o que de fato faz o fluxo de trabalho funcionar, e não a ferramenta tecnológica per si. Raciocínio análogo ao da necessidade de usuários, é ao problema dele que devemos nos balizar, e não na ferramenta tecnológica mais recente. Noutros termos, a lógica de organização dos sistemas que usamos não pode prescindir da nossa capacidade de reflexão e estabelecimento de regras para usá-los.

Creio que agora saltarão aos olhos as dificuldades dos órgãos públicos de se organizarem para o teletrabalho, nesse sentido - muito apego à conversa ao vivo (comunicação síncrona) e déficits de registro e texto corrido para representar as discussões e decisões. Particularmente sobre os itens 1, 6 e 9 das regras de etiqueta, estou vendo como está confuso para colegas de outros setores em tentar comunicar-se à distância e individualizar as tarefas de um plano de ação. A questão dos emails como forma de comunicação (item 11) também é um desafio enorme, pois tal comportamento me parece ser frequente em diversas organizações, tendemos a escrever conversas lá, quando a recomendação é que ele seja usado para conversas restritas e mensagens externas à organização.

Nossa experiência recente na DTA pode ajudar muito nisso. Uma vantagem em médio prazo desse método é forçar a pensar mais e obter mais conhecimento e autonomia, pois somos acostumados a buscar a informação onde ela está mais acessível (perguntando para o colega do lado) - na comunicação assíncrona e escrita, cada um se vê numa situação de busca e leitura individual. De outra forma, a dica 12 é um desafio pessoal também, compartilhar à medida que as ideias vão surgindo e registrá-las - penso que a cultura de entregar pronto é muito forte.

E, finalmente, pensar no tempo do outro, e não no próprio (está no meio da dica 15). O que se espera quando se ordena uma tarefa pode ser completamente influenciado da forma como ela é descrita. Isso induz uma reflexão mais profunda e qualificada de como se demandam os trabalhos. É a resposta pela resposta ou a finalidade que ela terá?

**Comment by kesiabomfa** [comment]
Bom, pra mim, o texto ainda é um desafio. Eu ainda tenho preferência pela comunicação síncrona. 
Mas, será necessário nos adaptar.
A regra 7 também é bem difícil, eu tenho a tendência a resolver os problemas mesmo que prematuramente. Tenho dificuldades em descansar enquanto não se resolve. E acredito tb que a sociedade cobra de nós uma solução.
A disponibilização do trabalho antes de ter terminado tb é outro desafio. 
O tele trabalho será um desafio em termos de discussões. Principalmente pq nem sempre conseguimos expor nossas dúvidas em texto, e ainda pode gerar interpretações diversas e diferentes daquelas propostas pelo autor.

**Comment by Andrelamor** [comment]
@kesiabomfa e demais colegas, vcs devem ter assinado os textos da Apolitical sobre [Transformação digital para servidores públicos](https://apolitical.co/transformacao-digital-microsserie/?utm_campaign=Boot%20Camps%2FCourse%20Drips&utm_source=hs_email&utm_medium=email&utm_content=85101391&_hsenc=p2ANqtz-8Lls-1GbqiPTb25oqKz2Z0hPTkl99vih6GqyE3KkAVrbQ7C18x3w_ESsoLjW0bv8O0rFWnBeE6Q_Rte3Qe2q1OyfZJRDukCuacFvUt0sg-iixpNfg&_hsmi=85101391). O texto desta série recebido hoje é [__Design centrado no ser humano: o desafio de colocar pessoas de volta ao centro das políticas públicas__](https://apolitical.co/design-focado-nas-pessoas-o-desafio-de-colocar-pessoas-de-volta-ao-centro-das-politicas-publicas/?utm_campaign=Boot%20Camps%2FCourse%20Drips&utm_source=hs_email&utm_medium=email&utm_content=85101391&_hsenc=p2ANqtz-8Lls-1GbqiPTb25oqKz2Z0hPTkl99vih6GqyE3KkAVrbQ7C18x3w_ESsoLjW0bv8O0rFWnBeE6Q_Rte3Qe2q1OyfZJRDukCuacFvUt0sg-iixpNfg&_hsmi=85101391). Além de ele ter relação com dois __issues__ já fechados (o primeiro e o último), tem uma parte dele que diz "SOMOS TREINADOS DESDE TENRA IDADE PARA RESOLVER PROBLEMAS, APONTANDO IMEDIATAMENTE RESPOSTAS A ESTES", recomendando "estar no lugar do problema por mais tempo do que você se sente confortável para isso". 
De fato também concordo contigo, é difícil 'conviver' ou 'aceitar' a permanência de um problema, ainda mais quando sabemos o início do caminho para resolvê-lo, mas não temos meios ou autonomia suficiente para iniciar o processo de solução.
Sobre as dubiedades de interpretação, recomendo a leitura do trecho "O ato de fazer sentido" [deste artigo](http://revista.ibict.br/ciinf/article/view/660/664) sobre a atividade humana de buscar a compreensão da realidade. Tem conceitos basilares nele de coisas que fazemos a todo instante para tentar nos comunicar de maneira razoável.

**Comment by silvianafaria** [comment]
Na minha opinião tanto a comunicação síncrona como a assíncrona apresenta vantagens e desvantagens. Concordo com o @Andrelamor quando ele cita que a _"A comunicação assíncrona exige muita disciplina_" e que não é a ferramenta em si que irá fazer o fluxo funcionar.

O cuidado que se deve ter ao utilizar as ferramenta de e-mail é não torná-lo uma ferramenta de bate-papo, pois não é essa a finalidade.  A comunicação assíncrona é valiosa quando utilizada de forma correta, pois conseguimos ter um registro dos pontos mais importantes de uma discussão. Mas, para isso a escrita deve ser bem clara para não ter ruídos, como destacado pela @kesiabomfa .

Ao que se refere a comunicação síncrona ela apresenta-se como mais confortável, pois obtemos o retorno imediato da dúvida/problema. Esse tipo de comunicação nos permite expôr ideias que muitas vezes são difíceis de colocar no papel.

Qual comunicação é melhor? A mais ideal?Em qual momento utilizar uma ou outra?
Na minha opinião depende do perfil de cada usuário de cada tarefa.

Eu particularmente prefiro a comunicação síncrona, isso porque sou uma pessoa que gosto de ter retorno das dúvidas de imediato. Mas, acredito que essa experiência que estamos passando no momento será super valiosa, no meu caso, me tira da zona de conforto, pois é o momento de praticar mais a comunicação assíncrona.

A comunicação assíncrona é bastante utilizada por mim apenas nos fóruns dos cursos que realizei.

**Comment by silvianafaria** [comment]
Ainda sobre a comunicação assíncrona, como destacado pelo @fjuniorr e no texto é muito importante fornecer o contexto, colocar exemplos e sempre que possível colocar a url.

@kesiabomfa  quanto ao citado por você _" ainda pode gerar interpretações diversas e diferentes daquelas propostas pelo autor_" acho que isso tornaria mais fácil a compreensão.

**Comment by fjuniorr** [comment]
Esbarrei em uma [ótima discussão](https://github.com/betterscientificsoftware/betterscientificsoftware.github.io/issues/375) sobre esse _blogpost_ na internet no contexto de [desenvolvimento de software científico](https://bssw.io/).
