### ISSUE TITLE
[Semanário] Aprendendo programação para comunicação técnica

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/lista-utilidades#5]
* [Conversational Programmers: The Trilogy](http://pgbovine.net/conversational-programmer-papers.htm). Philip Guo. 

Ps. Os artigos em si não fazem parte do escopo do semanário.

**Comment by silvianafaria** [comment]
Primeiramente acredito que me enquadro na metade que considera a programação como um meio para melhorar habilidades técnicas de comunicação e fazer pequenos trabalhos, como por exemplo o trabalho que estamos fazendo com a utilização do R.  

A área que atuamos na CGE, atualmente, está diretamente ligada a novas tecnologias, assim ampliar o conhecimento é necessário.

Entender a linguagem utilizada no mundo da tecnologia de informação é preciso principalmente para poder dialogar e exigir dos nossos parceiros, como por exemplo a Prodemge.

**Comment by kesiabomfa** [comment]
Gostei da descrição dos 93% que querem seguir carreiras que não exigem programação, mas que poderiam utilizar os conhecimentos para facilitar conversas técnicas, então, me encaixo nos grupo de programadores de conversação. Sem dúvida, entender um pouco mais de programação, ajudaria a dialogar com mais facilidade com a PRODEMGE e com os gestores dos sistemas corporativos.

E pontos que me chamaram atenção no texto e que tem tudo haver quando vou pesquisar algum assunto de programação, são:
- as explicações não são relevantes para as necessidades que estou procurando;
- e a facilidade de esquecer detalhes, se não usamos os recursos que aprendemos.

**Comment by Andrelamor** [comment]
Minha primeira impressão ao ler o artigo foi me sentir como o personagem de Robert de Niro no filme [Um senhor estagiário](http://www.adorocinema.com/filmes/filme-206217/) - ainda no início do filme e, claro, com 40 anos a menos. No início da minha jornada na CGE parecia que minha intenção ao tentar aprender alguma coisa de programação seria a mesma propalada pela dita pesquisa, mas o desejo de fato seria aprender para _não precisar_ do programador (ilusão que tento não alimentar mais). 

Tentando aproximar à nossa realidade, os achados podem ser sintomas de que a comunicação também precisaria ser melhorada na outra mão, dos programadores para os consumidores de dados - como @kesiabomfa tb comentou acima. Como faz falta umas aulinhas de redação pra essa geração de millennials! E talvez até __focar no problema do cliente__, entender minimamente suas regras de negócio, em vez de tentar empurrar pacotes de tecnologia como soluções-padrão, como já discutimos em _issue_ anterior.

**Comment by fjuniorr** [comment]
O resumo do resumo pra mim é

## Why do non-computer-science majors learn to code?

> We learned that roughly half of them saw programming as a tool for improving their technical communication skills and marketability for a variety of jobs that don't actually require them to write any code. 
> 
> […]
> 
> This perception intrigued us, so we coined a term called conversational programmer to describe these students who wanted to learn programming not to become programmers themselves but rather to facilitate technical conversations with programmers. One student summed up this sentiment well: “If we do anything [in] management we don't want to be standing there talking to someone not having a clue what they're talking about ... I couldn't do your [software development] job but when you're talking to me I [want to] know what you're saying.”

## Do conversational programmers exist out in the world?

> However, oftentimes the end goal of these activities was to use data or prototypes to hold more informed conversations with programmers. In other words, even the programming that they end up doing is ultimately in the service of facilitating conversations with others.

## How do conversational programmers learn to code?

> Our key discovery was that current learning resources are not well-suited for conversational programmers.

A minha experiência pessoal é passar por todas as etapas. A minha intuição é que no nosso ramo de atividade você não consegue produzir sem esse tipo de conhecimento.
