### ISSUE TITLE
[Semanário] Modelo de Referência para Publicação de Dados Abertos

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/lista-utilidades#6]
* [Modelo de Referência para Publicação de Dados Abertos](https://www.gov.br/cgu/pt-br/assuntos/noticias/2020/05/aberta-consulta-publica-sobre-modelo-de-referencia-para-publicacao-de-dados-abertos)

**Comment by Andrelamor** [comment]
![image](https://user-images.githubusercontent.com/52294411/86248706-9d752a00-bb84-11ea-8722-416c72cdfb84.png)

**Comment by Andrelamor** [comment]
Consegui entrar no link https://forms.office.com/Pages/ResponsePage.aspx?id=aSnJPlFaGE-Kye-Y-6-peCU05oA-1H1Epdzdks1wp5VURDRJV1FJVzI5TFhRUEVZNURFWjZXUTc2Qy4u. Não explicou qual o critério de seleção dos datasets a serem escolhidos (25) para abertura: 

Conjunto de dados não publicado no Portal dados.gov.br. Selecione até 25 itens

3.Gestão de Tecnologia da Informação e Comunicação (TIC) do Poder Executivo Federal
Base Nacional de Serviços Públicos para o Cidadão
Dados dos custos da transformação de serviços
Relação de órgãos que utilizam a malha da INFOVIA
Relação de softwares no Software Público Brasileiro (SPB)
Base de domínios gov.br

4.Gestão de Pessoas do Poder Executivo Federal
Programa de Desligamento Voluntário - PDV
Gastos de pessoal com Auxílios

5.Gestão Orçamentária da União
Informações do Projeto de Lei de Diretrizes Orçamentárias
Benefícios Financeiros e Creditícios

6. Gestão de Política Econômica
Dados Debêntures Emitidas - Lei 12.431 2011
Dados Portarias aptas a emitirem debêntures - Lei 12.431 2011

7.Comércio Exterior e Defesa Comercial
Sistema de Consultas sobre Tarifas, Regras de Origem e Serviços dos Acordos Comerciais Brasileiros
Lista de Empresas habilitadas aos benefícios do Acordo de Complementação Econômica 14 (ACE 14) e aos benefícios previstos na Resolução CAMEX nº 102/2018
Acompanhamento das Cotas de Importação
Lista consolidada de resultados de apuração nacional
Relatório de dados consolidados de drawback suspensão e isenção
Empresas usuárias de drawback suspensão e isenção
Apoio ao exportador brasileiro investigado por Defesa Comercial em outras jurisdições
Avaliações de Interesse Público em curso
Suspensões por interesse público em vigor

8.Desenvolvimento Industrial
Lista de Atos de Registro de Compromissos para comercialização no Brasil
Lista de Empresas Habilitadas ao Programa Rota 2030
Lista de Autopeças não produzidas
Programas Prioritários Credenciados
Estatísticas sobre Pleitos se Concessão ou Renovação de Ex-tarifários
Anúncios de Projetos de Investimentos

9.Políticas de Trabalho e de Emprego
Carteira de Trabalho e Previdência Socias - CTPS
Registro Profissional e de Contratante
Classificação Brasileira de Ocupações - CBO
Cadastro das empresas que trabalham com Benzeno
Cadastro das empresas que trabalham com Amianto
Sistema de Registro de Empresas de Trabalho Temporário
Sistema Mediador
Cadastro Nacional de Entidades Sindicais
Cadastro de Registro Eletrônico de Ponto
Cadastro de Equipamento de Proteção Individual
Programa de Alimentação do Trabalhador
Trabalho Análogo ao de Escravo
Sistema Nacional de Patrimônio - SINPAT
Sistema Nacional de Emprego - Sine Aberto
Planilha de Acompanhamento Gerencial do PNMPO
Sistema de Registro de Empresas de Trabalho Temporário - SIRETT
Sistema Juventudeweb - Consulta pública

10.Gestão de Modernização da Administração Pública
Relatórios de Monitoramento sobre os Contratos de Gestão firmados pelo ME

11.Gestão Logística da União
Sistema de Transportes de Servidores Públicos - TaxiGov

12.Gestão de Infraestrutura Nacional
Programa de Aceleração do Crescimento
Pró-Infra 2019

13.Administração Tributária
Ressarcimento de Crédito - REINTEGRA
Cronograma dos Lotes de Restituição do Imposto de Renda de Pessoa Física - IRPF
Valores dos Lotes de Restituição do Imposto de Renda de Pessoa Física - IRPF
Resultados da Fiscalização
Relatórios do Atendimento
Parcelamento de Débitos
Gastos Tributários
Desonerações Tributárias
Desoneração da Folha de Pagamentos
Resultado da Arrecadação
Taxa de Juros de Longo Prazo
Taxa de Juros Selic
Cadastro Nacional de Obras - CNO
Cadastro de Imóveis Rurais - CAFIR
Créditos Ativos

14.Administração Aduaneira
Movimentação e Tempos de Despachos Aduaneiros
Registro de Irregularidades Aduaneiras
Comércio Exterior por Nomenclatura Comum do Mercosul - NCM
Regime de Tributação Unificada
Destinações de Mercadorias Apreendidas

15.Gestão Previdenciária
Resultado do Regime Geral de Previdência Social
Acidentalidade por CNPJ
Auxílios-doença acidentários e previdenciários concedidos segundo os códigos da Classificação Nacional de Atividades Econômicas – CNAE 2.0
Valor Médio dos Benefícios emitidos pelo INSS
Demonstrativo de Informações Previdenciárias e Repasses
Demonstrativo de Resultados da Avaliação Atuarial
Parcelamento dos débitos
Demonstrativos de Aplicações e Investimentos dos Recursos
Benefícios mantidos pelo INSS
Demonstrativos de Aplicações e Investimentos dos Recursos
Certificado de Regularidade Previdenciária
Relatório de Informações Previdenciárias
Alíquotas de contribuição praticadas
Quantitativo de Regimes por UF
Histórico de Regime Previdenciário
Regime Previdenciário Atual dos Entes Federativos

16.Administração de Dívida Ativa
Estoque da dívida ativa
Estoque da dívida previdenciária
Estoque da dívida do FGTS

17.Considerando que essa iniciativa busca identificar o conjunto de dados a serem priorizados para abertura pelo Ministério da Economia, informe se há alguma base/conjunto não listado que gostaria de ver em nosso inventário
Todos os dados pessoais serão anonimizadas ou descartados ao final do processo de Consulta Pública
Insira sua resposta

18.Você tem alguma sugestão de melhoria para Conjunto de Dados já abertos pelo Ministério da Economia?
Todos os dados pessoais serão anonimizadas ou descartados ao final do processo de Consulta Pública
Insira sua resposta

19.Há alguma melhoria ou crítica que gostaria de nos informar sobre essa Consulta Pública?
Todos os dados pessoais serão anonimizadas ou descartados ao final do processo de Consulta Pública

**Comment by fjuniorr** [comment]
O documento está novamente no ar. [Aqui](https://www.gov.br/cgu/pt-br/governo-aberto/a-ogp/planos-de-acao/4o-plano-de-acao-brasileiro/compromisso-2-docs/modelo-de-referencia_revisado-e-formatado.pdf) existe inclusive o pdf.

Sobre o ponto de diminuir a fricção pra participar essa imagem resume o estado atual das soluções para consulta pública:

![Participa_br](https://user-images.githubusercontent.com/4969445/87100675-6c9b9180-c223-11ea-8e0f-3b39f488ddd2.png)
