### ISSUE TITLE
[Semanário] Processo de abertura de dados no município de São Paulo

### ISSUE THREAD

**Issue by fjuniorr** [transparencia-mg/lista-utilidades#9]
- [Traduções e desvios, mobilizações e desmobilizações na transparência pública: o processo de abertura de dados governamentais no município de São Paulo](https://bibliotecadigital.fgv.br/dspace/handle/10438/27669). Thomaz Silva.

**Comment by Andrelamor** [comment]
## Aspectos pontuados pelo Thomaz na experiência do município de São Paulo que são comuns à nossa:

* preponderância de comitês 'tecnicistas' de informática antes do reconhecimento da necessidade de abertura de dados (em MG, SEPLAG conta com reconhecimento amplos e contínuos a muitos anos, com a temática da digitalização de serviços, sem que isso esteja vinculado a uma política mais perene de governança, segurança, abertura e privacidade de dados);

* transferência de tecnologia sem a respectiva documentação (companhia de TI custodia documentos em vez das áreas de negócio);

* instabilidade institucional e mudança da responsabilidade dentre órgãos (aqui em MG tivemos o Escritório de Prioridades Estratégicas);

* diferentes capacidades institucionais para lidar com a temática de transparência e abertura de dados;

* Dados governamentais abertos como um conceito com baixa apreensão e baixa priorização pelos gabinetes das secretarias

### possíveis perguntas:

1. visão do papel coordenador/centralizador de um órgão central

2. possibilidades de inclusão da temática na agenda da compliance/Planos de Integridade

**Comment by Andrelamor** [comment]
questão importante de agenda:

> A entrada da ideia do CMBD na agenda pública municipal reside na influência de
atores externos, em um processo de disseminação de boas práticas de ações de
governos de outras esferas (no caso, o Governo do Estado de São Paulo) por meio
da sociedade civil, associada à captação dessa demanda por órgãos da PMSP

**Comment by Andrelamor** [comment]
> Em 2018, foi implementado pela Divisão de Transparência Ativa o processo de
atualização semestral do CMBD juntos dos órgãos e entidades da PMSP. Com esta
ação pretendemos fortalecer os procedimentos de registro das bases de dados
gerenciadas e criadas pela Prefeitura, além de fomentar um acompanhamento mais
próximo e com registro sempre atualizado destas informações. Também foi iniciado o
processo de realização de diagnósticos sobre as bases de dados da Prefeitura para a
abertura destes à população em formato aberto, que será de grande importância para
o cumprimento desta meta.
Como resultado deste processo, no segundo levantamento do CMBD em 2018 foram
coletadas informações sobre 782 bases de dados (um acréscimo de 38 novas bases
sistematizadas em relação ao valor anterior de 744 bases de dados), representando
um acréscimo de 5,10%.
Do total de bases de dados, 169 (21,61%) estão em formato aberto, são processáveis
por máquinas e estão disponíveis a toda a população. Ou seja, nota-se um aumento
percentual de 1,18%, considerando-se o crescimento de 20,43% no primeiro
levantamento do CMBD em 2018, para 21,61% do levantamento atual. Desta forma, o
total absoluto de bases abertas aumentou de 152 para 169 bases, ou seja, um aumento
de 17 bases de dados abertas

**Comment by fjuniorr** [comment]
Vou colocar algumas citações pouco organizadas para fins de registro.

## Topico

> Na Sociologia da Tradução - ou, como é mais conhecida, na Teoria Ator-Rede - dizer que algo foi colocado na caixa-preta diz respeito à internalização de uma prática pelos atores de uma rede, de forma com que as complexidades por trás daquele processo tornam-se invisíveis e não notadas na prática cotidiana, ou seja, tornam-se dadas por si próprias (LATOUR, 2011). Em bom português, colocar algo na caixa-preta, no sentido dos processos que envolvem tecnologia, pode ser transladado como ‘fazer as coisas no automático’
> 
> [...]
> 
> caixas-pretas também trazem a ideia de “redes de atores seladas nas quais os alinhamentos foram obtidos e nas quais os interesses alinhados foram inscritos em associações estáveis que não são mais questionadas” (SHIN, 2010, p. 149, tradução nossa), dirimindo controvérsias e estabelecendo entendimentos mútuos (BITTENCOURT, 2014, p. 116–123; PAULICS, 2003, p. 29–31), ou, no entendimento comum, ‘dando o caso como encerrado’ (pelo menos momentaneamente). [pg. 23]

> Neste ponto, há algo interessante ainda a se descobrir: como lidar com as complexidades que surgem quando saímos de uma caixa-preta internalizada por anos na Administração Pública (manter os dados e informações do setor público longe dos
olhos da sociedade) para uma outra caixa-preta – hoje, tecnologicamente possível - relacionada com a disponibilização dos dados de forma inteiramente automatizada, sem passar por manipulações dos atores humanos, de forma com que os processos de abertura já fossem previamente calculados e menos sujeitos às desmobilizações conjunturais? [pg. 25]

> Percebemos que da caixa-preta do segredo para a caixa-preta da transparência cada base de dados é única e, portanto, as redes de atores humanos e não-humanos por detrás delas devem ser consideradas na implementação dos processos de abertura. [pg. 25]

Práticas positivas e negativas podem ser colocadas na caixa preta.

> O objetivo principal desta tese é investigar como os processos de abertura de dados governamentais ocorrem na prática. A partir dessa ideia emergem discussões relativas a diferentes problemáticas, tais como: 
> 
> - a inserção de novas temáticas na agenda governamental; 
> - a implementação de processos de inovação tecnológica no setor público; 
> - a coordenação e a articulação de políticas públicas; 
> - as capacidades institucionais relativas à gestão da informação e gestão da tecnologia da informação nos governos subnacionais, dentre outras. 

Nos projetos de abertura de bases de dados que estamos vivendo as dificuldades "ainda" não são explicitamente sobre o caratér "público" dos dados. Nem mesmo na COVID-19 essa foi a dificuldade principal.

> a gestão da informação; a gestão dos sistemas de informação; e a gestão dos processos de   abertura em si
(silva2019, p.83)

> O desenvolvimento se deu através de contrato firmado por SEMPLA e empresa terceirizada que, além de realizar a configuração inicial do SharePoint, desenvolveu os sistemas hospedados por ele, em sua maioria utilizando o NET. Posteriormente, o Portal e seus sistemas foram transferidos e internalizados na Prodam - sem seus respectivos códigos fontes. 
(silva2019, p.87)

> Da Transparência Ativa já havia umas certas disputas. E uma disputa que a Controladoria já entrou enfraquecida, porque ela não tinha estrutura. Então, nos primeiros momentos, a gente realmente precisou acomodar esse entendimento, até com a Secretaria de Finanças, que tocava o Portal da Transparência e tal. Mas, entendendo que a Controladoria dava as diretrizes, mas quem executava, operacionalizava naquele momento era a Secretaria de Finanças. E também havia outros interesses: a Secretaria de Planejamento também queria tocar algumas pautas de Dados Abertos, mas a pauta de acesso à informação acho que houve um entendimento de toda a prefeitura na época de que era atribuição da Controladoria.
(silva2019, p.91)

## Topico

> no que tange à sua Diretoria de Transparência Ativa, por dois servidores públicos que possuíam uma experiência anterior na área de Tecnologia da Informação em outros órgãos da PMSP.
(silva2019, p.94)

> Esta estrutura de uma Diretoria de Transparência Ativa composta por dois ou três servidores é algo que vêm se mantendo ao longo do tempo e demonstra o quanto sua estrutura é inadequada para coordenar as ações relativas à implementação da agenda de transparência ativa frente ao tamanho da estrutura da PMSP.
(silva2019, p.94)

> Tais resistências, na época, foram parcialmente vencidas por meio do empreendedorismo político do gestor da pasta e do próprio prefeito, que viu na abertura de dados públicos uma forma de oferecer à sociedade os meios necessários para ampliar o debate público sobre a questão do aumento e da qualidade do transporte urbano.   
(silva2019, p.96)

> E aí quando a gente foi para fora do departamento, para outras áreas da   secretaria, para outras áreas da prefeitura, você constrói um processo. “Olha,   a gente está em um processo de organização dos dados, e tal, para   publicação. Vão ter tais etapas...”. Você prepara as pessoas para elas   entrarem no projeto, porque senão... Aconteceu muito também… A primeira   fase é inventário de dados. Aí você manda para um cara que você sabe que   tem um monte de dados, e o cara “Ah, mas eu não tenho nada de diferente”.   O cara tem, só que - porque ele trabalhou lá, ele construiu uma camada de   largura de vias que ninguém tem, só que ele não vai te entregar de bandeja,   assim. Ele vai falar: “ah, tenho, mas é um negócio que fiz mais ou menos...”.   Você o chama para um processo de inventário, de metadados. Aí ele vê uma   utilidade. Daí ele “Beleza, isso aí vai ser um projeto que vai acabar me ajudando a organizar essa... vai me dar um tempo para organizar essa coisa.”.   Você monta lá o grupo, o Secretário indica as pessoas. Aí ela tem uma justificativa para usar o tempo para organizar os dados. Então é muito essa   construção que você tem que ir fazendo
(silva2019, p.95)

> No entanto, as dificuldades que se seguiram para a implementação do catálogo demonstram que os órgãos da Prefeitura não estavam acostumados a olhar para a gestão da informação de uma forma integrada, demandando um esforço muito maior do que o originalmente pensado e atingindo resultados aquém daqueles inicialmente  previstos.
(silva2019, p.95)

> Contudo, uma das questões que podem ser notadas na própria Política Municipal de Governança de Tecnologia da Informação e Comunicação – PMGTIC é a ausência de qualquer referência ao conceito de dados governamentais abertos em seu texto, apesar de uma das diretrizes da política ser justamente a transparência e a participação social. Detectada essa ausência e diante da necessidade de todos os órgãos terem que elaborar seus Planos Diretores Setoriais de Tecnologia da Informação e Comunicação – PDSTIC, um dos possíveis campos de ações da CPIN-SMIT para fortalecimento da rede de abertura de dados - com uma proposta de associação ao invés de substituição – residiria no incentivo de uma articulação junto aos órgãos da PMSP para incluírem em seus PDSTICs linhas de ações que estivessem relacionadas à transparência e participação social, na perspectiva de dados governamentais abertos já apresentada neste estudo. 
(silva2019, p.99)

## Topico

> No entanto, houve um desvio em relação à essa pergunta pois a própria CGM,   responsável pela gestão do eSIC-SP, orientou os órgãos para responderem à  pergunta de forma a invocarem que as ações relativas à meta deveriam ser   perguntadas diretamente àquele órgão. Com essa orientação, o que se viu é que a   maioria dos órgãos se abstiveram de responder quais foram as ações desenvolvidas   internamente para abrirem as suas próprias bases, algo que consideramos como   bastante equivocado pois, mesmo estando a meta sob coordenação da CGM-SP, a   responsabilidade pelo cumprimento da legislação municipal que determina a  divulgação ativa das informações públicas é do próprio órgão, não da Controladoria.  Na resposta oferecida pela Secretaria do Governo Municipal, fica clara essa confusão,   já que o órgão afirma que “conforme alinhamento junto à Controladoria Geral do   Município, solicitamos que informações adicionais referentes às ações para a   realização da Meta 49 do Programa de Metas 2017-2020 sejam encaminhadas àquele   órgão”
(silva2019, p.110)

> O que essas duas respostas demonstram é que, havendo uma preocupação interna   diretamente focada para a abertura de dados governamentais, os órgãos municipais   começam a agir em direção à organização dos setores e melhor condução desses   processos.
(silva2019, p.112)


## Topico

> A rotina para a abertura das bases de dados, portanto, precisou incluir também um   processo de manejo dos arquivos para que as diferentes bases de dados do sistema   fossem reunidas em um único arquivo, 
(silva2019, p.117)

> tanto é que tinha uma pessoa lá que trabalha com isso fazendo esta parte,   mas, assim, seria fora até do escopo do setor. É que tem uma pessoa, duas,   na verdade, que sabiam essa parte da informática, então elas faziam essa   automatização. Mas sem essas pessoas, por exemplo, elas deixando algum   código, algum procedimento, é difícil alguém leigo fazer a parte da informática.   É um processo bem complicadinho. São várias tabelas para poder mexer,   você precisa ter essa noção do Access, pois ele vem em Access. Para   transformar isso no Excel é puxado. (eSIC-SP: D302: 7)
(silva2019, p.117)

> A gente se reuniu numa força tarefa, fez a revisão dos pedidos de acesso à  informação, todos os servidores sentaram lá numa planilha de Excel, com uma   dupla checagem para anonimizar os pedidos, em um esforço que a própria   CGU, quando disponibiliza os dados, os pedidos de acesso à informação, não   repete esse cuidado, ela divulga as informações pessoais, CPF, RG do   solicitante, que no nosso entendimento na época era bastante temerário.   Informações pessoais solicitadas, é delicado. E aí a gente anonimizava,   anonimizou, foi um trabalho longo, foram algumas semanas de trabalho. Mas,   assim, teve um resultado gratificante.
(silva2019, p.118)

> Um detalhe importante é que essa plataforma foi construída a partir do código-fonte   de um outro projeto de abertura de dados que havia sido lançado anteriormente, o   Diário Livre, que será o objeto do próximo estudo de caso. Como todo o projeto do   estava disponível na plataforma GitHub, a coordenadora da COPI-CGM na época   aproveitou os códigos da plataforma do Diário Livre e construiu a plataforma dos  Pedidos Respondidos em cima da programação previamente disponibilizada48  .
(silva2019, p.119)

> Atualmente, um dos principais desafios para a manutenção do processo de abertura  continua sendo a sua anonimização. 
(silva2019, p.121)

> Possibilitou à própria Coordenadoria de Promoção da Integridade adquirir um   conhecimento prático de processos de anonimização e de estruturação de   bases de dados, utilizando a experiência como insumo nas oficinas oferecidas   aos demais órgãos da prefeitura (eSIC-SP, D306: 6);  
(silva2019, p.123)

> sempre tinha essa tentativa de fazer chegar o conceito de que existe muito   debate – até hoje ainda é um pouco assim, eu acho, mas na época era muito   assim – de que transparência quer dizer do gasto. Então, o Portal da   Transparência é gasto. Tem que dar transparência para o gasto. A gente   falava “não, tem um monte de coisa, tem um monte de ação da gestão pública   que é muito relevante e que não é gasto”. 
(silva2019, p.139)

> “os dados nasciam abertos e morriam fechados, porque eles já eram   mandados para Imprensa Oficial como TXT e depois eles transformavam em PDF.
(silva2019, p.141)

> quem produz os dados é muito responsável pela abertura de dados. Porque   ele sabe o processo, ele sabe que fase, inclusive, mesmo que não seja   exatamente criado para abrir os dados, ele pode sugerir ou intervir ali para   captar esses dados e canalizar ele para desenvolver uma abertura.
(silva2019, p.141)

> O fato é que com esses dois novos fatos (o acesso às bases do DOC-SP desde 2003   e a possibilidade de atualização diária através do arquivo zipado recebido pela SMG),   surge, enfim, uma oportunidade concreta para que esses arquivos compusessem a   base necessária para o desenvolvimento de um projeto de abertura dessas bases   pelo Colab-USP, visto que na COPI-CGM “não tinha um corpo técnico para fazer essa   amarração” (DOC-SP, D204: 2).  
(silva2019, p.142)

> A gente se inscreveu em um curso do GovLab como equipe COPI, (...) era um   curso de open contracting e a gente tomou como objeto do nosso esforço ali   aprimorar a forma como eram publicados os dados de licitação a partir do   Diário Livre. E aí a gente percebeu que a gente precisava, para adotar o   Diário Livre como ferramenta, para abrir os dados do Diário Oficial, a   gente precisava melhorar a forma como eles eram publicados. Então a   gente precisava começar a estruturar eles desde o início, ter os campos   específicos de metadados. E aí a gente não queria dificultar para os   servidores. A gente fez levantamento e, por exemplo, tinha 700, 800 usuários   na Prefeitura que faziam alguma publicação no Diário Oficial. Que, então,   esses usuários precisariam ser capacitados. Para padronizar alguma coisa a   gente não poderia dificultar o trabalho dessas pessoas, a gente teria que   apoiar. Então teria que ser uma ferramenta. A gente começou a pensar num   editor de texto. Para melhorar isso, a gente precisaria construir um editor de   texto, que tem uma interface amigável, que ele digita algumas coisas e que o   editor cospe para ele num formato que precisa ir para o Diário Oficial, ele não   precisa ficar preenchendo aquelas tags manualmente. As vezes erra e tal. Só   precisaria preencher alguns metadados na tela, por lá no campo de texto e ele   geraria um arquivo para o Diário Oficial. Foi a maneira como a gente pensou   que ia gerar um valor para os servidores, para eles adotarem a ferramenta.   Mas a Gestão precisaria estar muito comprada nisso. E isso também não   foi priorizado. (DOC-SP, D203: 22 – D203: 26, grifos nossos)  
(silva2019, p.145)

> Outro problema surgido nesta fase se relaciona com as codificações dos TXTs. Como   alguns arquivos tinham codificações diferentes entre si, foi necessário descobrir como   cada arquivo estava codificado. 
(silva2019, p.146)

> Conforme Martano (2015, p. 72), “É importante notar aqui que a equipe da COPI-CGM não dispunha   de uma equipe técnica capaz de resolver o problema. Além disso, o fato de só disporem de máquinas   Windows, dificultava a ajuda por parte do programador do Colab-USP que havia automatizado o   restante do processo (...)”.
(silva2019, p.148)

> Como a IMESP e a PMSP não permitiram o acesso direto do Colab-USP ao protocolo   FTP, decidiu-se, em um primeiro momento, que a alimentação seria feita   manualmente por servidores públicos da COPI-CGM, os quais, diariamente,   submeteriam o arquivo zipado para um programa de compartilhamento de arquivos   (OwnCloud) hospedado em um servidor da Colab-USP. Como esse procedimento   gerava atrasos constantes na alimentação do Diário Livre e como a COPI-CGM não   conseguia automatizar esta rotina75, após seis meses de alimentação manual, o   LabProdam, laboratório de inovação da Prodam recém-criado na época, desenvolveu   uma automatização por meio da ferramenta WebDAV, capaz de disponibilizar o   arquivo ao servidor da Colab-USP por meio de um protocolo HTTP.  Desta forma, como lembram Craveiro, Alcazar e Martano (2016, p. 117, tradução   nossa), “devido a evolução do processo de negociação que envolvia a obtenção de   dados dos poderes públicos, o estágio de implementação da extração automatizada   para atualização diária dos dados só pode ser completamente integrada ao sistema   no final de sua implementação”. Mesmo assim, conforme relato de uma das pessoas   entrevistadas, a ferramenta elaborada pelo LabProdam começou a dar erro e,   portanto, voltou-se ao processo de alimentação manual (DOC-SP, D208: 7).  
(silva2019, p.148)

> O fato de haver servidores na COPI-CGM que sabiam como se dava o processo de   alimentação da base foi um facilitador no processo pois, assim, foram buscadas   algumas alternativas internas para a abertura da base de dados. 
(silva2019, p.154)

> De fundamental importância para o processo de abertura foi o acesso aos arquivos   de todas as matérias do jornal publicadas desde 2003, armazenados casualmente no   computador de trabalho de uma pessoa da CGDOC-SMG.   
(silva2019, p.155)

> “Apesar do código do sistema e dos scripts relacionados estarem abertos, e de   algumas funcionalidades e correções terem sido requisitadas, nenhum desenvolvedor   externo à equipe e à prefeitura, contribuiu no desenvolvimento do sistema.”.  
(silva2019, p.157)

> “Uma questão relevante e ainda em aberto é quanto à internalização do sistema pela   prefeitura, uma vez que ele continua hospedado no servidor do Colab-USP. Tendo   em vista que o sistema foi desenvolvido de forma experimental, a internalização do   mesmo não está garantida, o que pode comprometer sua existência a longo prazo.”. 
(silva2019, p.157)

> Isso exige um investimento grande. Você reorganizar, antes, tem um monte   de coisa técnica, mas você precisa reorganizar a base cartográfica da cidade,   transformar um banco de dados em um banco de dados relacional, porque   isso facilita a conectividade entre as camadas. Preciso desenhar e construir   fluxos entre os diferentes sistemas. Aí, de fato, você consegue um grande   salto. Pensar projetos estruturantes de organização dos dados e de   publicação, eu acho que é o principal. A partir daí vários frutos saem. Os   dados do IPTU não teriam sido publicados só na marretada. Foram   publicados porque você começa a ter um negócio maior, que tem corpo, que   tem uma lógica mais sistêmica. Não é uma iniciativa pessoal de ninguém. É   um projeto que as pessoas olham e enxergam: “Nossa, isso aqui é um ganho   para a Administração”. Então eu acho que esse é o principal fator. Como   poderia, deveria ter uma Infraestrutura Municipal de Dados Abertos. Só que   isso aí exige fôlego. “Ah, eu quero ficar um ano na Prefeitura”. Não, você tem   que olhar e falar, em quatro anos, onde eu quero chegar, o que eu quero   construir. Aí ir atrás de recurso, que é sempre melhor no começo do governo.   Gerar resultados parciais. Você tem que tocar um projeto grande. Aí você vai   trazendo as pessoas. E aí, isso, os projetos estruturantes, abrem espaço para   investimentos em qualidade da informação que sejam mais coerentes.
(silva2019, p.178)

> Nas entrevistas detectamos que a abertura de bases de dados governamentais nem   sempre geram impactos políticos positivos ao governo. Como muitas vezes a abertura   dos dados públicos geram mais notícias negativas em relação aos conteúdos   revelados pelos dados do que notícias positivas em relação à abertura em si, os   incentivos políticos para a abertura de dados governamentais são extremamente   baixos. 
(silva2019, p.179)

> Por outro lado, perceber que governos mais transparentes, mesmo   revelando aspectos negativos sobre o próprio governo, são mais democráticos do que   governos não transparentes, demanda maior responsabilidade e maturidade política  da própria sociedade, pois quando os dados governamentais são abertos, seus   conteúdos quase sempre revelam aspectos problemáticos nas gestões. 
(silva2019, p.180)

> Como mobilizadores organizacionais, os principais pontos apresentados estão   relacionados com uma equipe com um conhecimento técnico mínimo em relação à   tecnologia e bases de dados, que esteja bem formada sobre as questões conceituais   envolvidas nestes processos (Geral, D400:10), uma vez que a ausência de servidores   com este tipo de conhecimento dificulta iniciativas de abertura (Geral, D402: 11).   Muitas vezes, por trás de processos de abertura, não estão problemas relacionados   à abertura em si, mas, problemas anteriores, relacionados à gestão da informação. 
(silva2019, p.180)

## Topico

> a segunda é que há um trabalho de convencimento   constante ainda necessário a ser feito junto aos órgãos da Administração Pública, o   qual demanda mais um trabalho horizontalizado de cooperação entre os órgãos do   que de imposição de cima para baixo. (silva2019, p.184)

> todos os trabalhos que são feitos em conjunto com as equipes e não vira uma   coisa de cima para baixo, eu acho que eles acabam sendo uma coisa mais   respeitada, as pessoas abraçam a causa de forma mais fácil, o servidor. (silva2019, p.182)

## Topico

> Bom, definitivamente, segurança do servidor que trabalha com a base de   dados para fazer a disponibilização desses dados. Acho que esse é o   elemento essencial. Essa segurança tanto, assim, a segurança política (“eu   vou disponibilizar esse dado e não vou ser penalizado por isso, porque eu   estou cumprindo a lei, então está tudo bem”). Então, segurança, tanto política   quanto, ele precisa saber o que ele está fazendo, então técnica. Segurança   técnica: “eu posso mexer nesse dado dessa forma, se eu anonimizar assim 
(silva2019, p.183)

> vai estar anonimizado mesmo, se eu disponibilizar assim, as pessoas não vão   fraudar essa informação”. Porque, no fim das contas, é só ter um lugar, uma   fonte, é uma segurança muito maior do que o formato que está sendo   disponibilizado os dados, enfim. Acho que esse seria um fator primordial.   Segurança do servidor que trabalha diretamente com essa base. (Geral,   D409: 1) (silva2019, p.184)

> Com a informação respondida, também conseguimos responder uma das indagações   que fizemos na introdução desta tese, tentando identificar quais eram as dificuldades   em relação à possibilidade de tornar a abertura de dados governamentais uma prática   consensuada e sem controvérsias no desenvolvimento de sistemas de tecnologia de   informação, sendo possível identificar pelo menos duas desmobilizações: a primeira  relacionada aos recursos orçamentários; a segunda relacionada à proteção dos   dados pessoais. (silva2019, p.197)
